SystemOrganization addCategory: #Espell!
SystemOrganization addCategory: 'Espell-Debug'!
SystemOrganization addCategory: 'Espell-HighLevel'!
SystemOrganization addCategory: 'Espell-LowLevel-Mappings'!
SystemOrganization addCategory: 'Espell-LowLevel-Mirrors'!
SystemOrganization addCategory: 'Espell-LowLevel-Primitives'!
SystemOrganization addCategory: 'Espell-Support'!
SystemOrganization addCategory: 'Espell-Tests'!
